fs     = require 'fs'
{exec} = require 'child_process'

appFiles  = [
  'app',
  'delegator',
  'utils',
  'slider',
  'sunburst',
  'barchart',
  'barchart-panel',
  'tooltip',
  'bootstrap'
]

task 'build', 'Build single application file from source files', ->
  appContents = new Array remaining = appFiles.length

  for file, index in appFiles then do (file, index) ->
    fs.readFile "src/#{file}.coffee", 'utf8', (err, fileContents) ->
      throw err if err
      appContents[index] = fileContents
      process() if --remaining is 0

  process = ->
    fs.writeFile 'js/app.coffee', appContents.join('\n\n'), 'utf8', (err) ->
      throw err if err
      exec 'coffee --compile js/app.coffee', (err, stdout, stderr) ->
        throw err if err
        console.log stdout + stderr
        fs.unlink 'js/app.coffee', (err) ->
          throw err if err
          console.log 'Done.'

task 'minify', 'Minify the resulting application file after build', ->
  exec 'java -jar "/home/andrea/bin/closure-compiler.jar" --js js/app.js --js_output_file js/app.production.js', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr
