source "http://rubygems.org"

group :development do
  gem "pry"
  gem "coffee-script"
  gem "rack-coffee"
end

group :default do
  gem "ohm"
  gem "ohm-contrib"
  gem "sinatra", :require => "sinatra/base"
  gem "sinatra-contrib"
  gem "nokogiri"
end



